// productos.js

let productos = [
    { id: 1, nombre: 'Riquitos Papas Fritas', descripcion: '', precio: 3290, imagen: 'img/rick-papa.png' },
    { id: 2, nombre: 'Riquitos Chizitos', descripcion: '', precio: 1800, imagen: 'img/rik-chizito.png' },
    { id: 3, nombre: 'Riquitos Palitos', descripcion: '', precio: 1350, imagen: 'img/rik-pal.png' },
    { id: 4, nombre: 'Riquitos Mani', descripcion: '', precio: 3540, imagen: 'img/rik-mani.png' },
    { id: 5, nombre: 'Leq Papas Fritas', descripcion: '', precio: 33570, imagen: 'img/leq-papa.png' },
    { id: 6, nombre: 'Leq Chizitos', descripcion: '', precio: 1780, imagen: 'img/leq-chizito.png' },
    { id: 7, nombre: 'Leq Palitos', descripcion: '', precio: 1670, imagen: 'img/leq-pal.png' },
    { id: 8, nombre: 'Leq Mani', descripcion: '', precio: 1150, imagen: 'img/leq-mani.png' },
    { id: 9, nombre: 'Easy Beef-Fargo', descripcion: '20 hamburguesas de 110 grs con pan y aderezo ', precio: 10990, imagen: 'img/easyfargo.png' },
    { id: 10, nombre: 'Easy Beef-Mimago', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 8230, imagen: 'img/easymimago.png' },
    { id: 11, nombre: 'Easy Beef-Pan Artesanal', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 8420, imagen: 'img/easyart.png' },
    { id: 12, nombre: 'La Defensa-Fargo', descripcion: '20 hamburguesas de 110 grs con pan y aderezo ', precio: 11110, imagen: 'img/defe-fargo.png' },
    { id: 13, nombre: 'La Defensa-Mimago', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 8340, imagen: 'img/def-mm.png' },
    { id: 14, nombre: 'La Defensa-Pan Artesanal', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 8530, imagen: 'img/def-art.png' },
    { id: 15, nombre: 'Kandy-Fargo', descripcion: '20 hamburguesas de 110 grs con pan y aderezo ', precio: 11500, imagen: 'img/kandyfargo .png' },
    { id: 16, nombre: 'kandy-Mimago', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 8740, imagen: 'img/kandymimago.png' },
    { id: 17, nombre: 'Kandy-Pan Artesanal', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 8930, imagen: 'img/kandyart.png' },
    { id: 18, nombre: 'La Conquista-Fargo', descripcion: '20 hamburguesas de 110 grs con pan y aderezo ', precio: 12820, imagen: 'img/laconq-fargo.png' },
    { id: 19, nombre: 'La Conquista-Mimago', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 10050, imagen: 'img/laconq-mm.png' },
    { id: 20, nombre: 'La Conquista-Pan Artesanal', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 10240, imagen: 'img/laconq-art.png' },
    { id: 21, nombre: 'Pronto Beef-Fargo', descripcion: '20 hamburguesas de 110 grs con pan y aderezo ', precio: 13420, imagen: 'img/pronto-fargo.png' },
    { id: 22, nombre: 'Pronto Beef-Mimago', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 10660, imagen: 'img/pronto-mm.png' },
    { id: 23, nombre: 'Pronto Beef-Pan Artesanal', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 10850, imagen: 'img/pronto-art.png' },
    { id: 24, nombre: 'Victoria-Fargo', descripcion: '20 hamburguesas de 110 grs con pan y aderezo ', precio: 14290, imagen: 'img/victoria-fargo.png' },
    { id: 25, nombre: 'Victoria-Mimago', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 11530, imagen: 'img/victoria-mm.png' },
    { id: 26, nombre: 'Victoria-Pan Artesanal', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 11720, imagen: 'img/victoria-art.png' },
    { id: 27, nombre: 'Rancho Alto-Fargo', descripcion: '20 hamburguesas de 110 grs con pan y aderezo ', precio: 16190, imagen: 'img/rancho-fargo.png' },
    { id: 28, nombre: 'Rancho Alto-Mimago', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 13430, imagen: 'img/rancho-mm.png' },
    { id: 29, nombre: 'Rancho Alto-Pan Artesanal', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 13620, imagen: 'img/rancho-art.png' },
    { id: 30, nombre: 'Paty-Fargo', descripcion: '20 hamburguesas de 125 grs con pan y aderezo ', precio: 16190, imagen: 'img/paty-fargo.png' },
    { id: 31, nombre: 'Paty-Mimago', descripcion: '20 hamburguesas de 125 grs con pan y aderezo', precio: 13430, imagen: 'img/paty-mm.png' },
    { id: 32, nombre: 'Paty-Pan Artesanal', descripcion: '20 hamburguesas de 125 grs con pan y aderezo', precio: 13620, imagen: 'img/paty-art.png' },
    { id: 33, nombre: 'Maxi Mesa-Fargo', descripcion: '20 hamburguesas de 110 grs con pan y aderezo ', precio: 11500, imagen: 'img/maxi-fargo.png' },
    { id: 34, nombre: 'Maxi Mesa-Mimago', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 8740, imagen: 'img/max-mm.png' },
    { id: 35, nombre: 'Maxi Mesa-Pan Artesanal', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 8930, imagen: 'img/max-art.png' },
    { id: 36, nombre: 'Boogys-Fargo', descripcion: '20 hamburguesas de 110 grs con pan y aderezo ', precio: 12820, imagen: 'img/boogiesfargo.png' },
    { id: 37, nombre: 'Boogys-Mimago', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 10050, imagen: 'img/boog-mm.png' },
    { id: 38, nombre: 'Boogys-Pan Artesanal', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 10240, imagen: 'img/boog-art.png' },
    { id: 39, nombre: 'Union Ganadera-Fargo', descripcion: '20 hamburguesas de 110 grs con pan y aderezo ', precio: 13420, imagen: 'img/union-fargo.png' },
    { id: 40, nombre: 'Union Ganadera-Mimago', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 10660, imagen: 'img/union-mm.png' },
    { id: 41, nombre: 'Union Ganadera-Pan Artesanal', descripcion: '20 hamburguesas de 110 grs con pan y aderezo', precio: 10850, imagen: 'img/victoria-art.png' },
    { id: 42, nombre: 'Maxi Mesa-Fargo', descripcion: '20 hamburguesas de 125 grs con pan y aderezo ', precio: 14290, imagen: 'img/maxi-fargo.png'  },
    { id: 43, nombre: 'Maxi Mesa-Mimago', descripcion: '20 hamburguesas de 125 grs con pan y aderezo', precio: 11530, imagen: 'img/max-mm.png' },
    { id: 44, nombre: 'Maxi Mesa-Pan Artesanal', descripcion: '20 hamburguesas de 125 grs con pan y aderezo', precio: 11720, imagen: 'img/max-art.png' },
    { id: 45, nombre: 'Easy Beef-Fargo', descripcion: '40 hamburguesas de 110 grs con pan y aderezo ', precio: 10990, imagen: 'img/easyfargo.png' },
    { id: 46, nombre: 'Easy Beef-Mimago', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 8230, imagen: 'img/easymimago.png' },
    { id: 47, nombre: 'Easy Beef-Pan Artesanal', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 8420, imagen: 'img/easyart.png' },
    { id: 48, nombre: 'La Defensa-Fargo', descripcion: '40 hamburguesas de 110 grs con pan y aderezo ', precio: 11110, imagen: 'img/defe-fargo.png' },
    { id: 49, nombre: 'La Defensa-Mimago', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 8340, imagen: 'img/def-mm.png' },
    { id: 50, nombre: 'La Defensa-Pan Artesanal', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 8530, imagen: 'img/def-art.png' },
    { id: 51, nombre: 'Kandy-Fargo', descripcion: '40 hamburguesas de 110 grs con pan y aderezo ', precio: 11500, imagen: 'img/kandyfargo .png' },
    { id: 52, nombre: 'kandy-Mimago', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 8740, imagen: 'img/kandymimago.png' },
    { id: 53, nombre: 'Kandy-Pan Artesanal', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 8930, imagen: 'img/kandyart.png' },
    { id: 54, nombre: 'La Conquista-Fargo', descripcion: '40 hamburguesas de 110 grs con pan y aderezo ', precio: 12820, imagen: 'img/laconq-fargo.png' },
    { id: 55, nombre: 'La Conquista-Mimago', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 10050, imagen: 'img/laconq-mm.png' },
    { id: 56, nombre: 'La Conquista-Pan Artesanal', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 10240, imagen: 'img/laconq-art.png' },
    { id: 57, nombre: 'Pronto Beef-Fargo', descripcion: '40 hamburguesas de 110 grs con pan y aderezo ', precio: 13420, imagen: 'img/pronto-fargo.png' },
    { id: 58, nombre: 'Pronto Beef-Mimago', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 10660, imagen: 'img/pronto-mm.png' },
    { id: 59, nombre: 'Pronto Beef-Pan Artesanal', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 10850, imagen: 'img/pronto-art.png' },
    { id: 60, nombre: 'Victoria-Fargo', descripcion: '40 hamburguesas de 110 grs con pan y aderezo ', precio: 14290, imagen: 'img/victoria-fargo.png' },
    { id: 61, nombre: 'Victoria-Mimago', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 11530, imagen: 'img/victoria-mm.png' },
    { id: 62, nombre: 'Victoria-Pan Artesanal', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 11720, imagen: 'img/victoria-art.png' },
    { id: 63, nombre: 'Rancho Alto-Fargo', descripcion: '40 hamburguesas de 110 grs con pan y aderezo ', precio: 16190, imagen: 'img/rancho-fargo.png' },
    { id: 64, nombre: 'Rancho Alto-Mimago', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 13430, imagen: 'img/rancho-mm.png' },
    { id: 65, nombre: 'Rancho Alto-Pan Artesanal', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 13620, imagen: 'img/rancho-art.png' },
    { id: 66, nombre: 'Paty-Fargo', descripcion: '40 hamburguesas de 125 grs con pan y aderezo ', precio: 16190, imagen: 'img/paty-fargo.png' },
    { id: 67, nombre: 'Paty-Mimago', descripcion: '40 hamburguesas de 125 grs con pan y aderezo', precio: 13430, imagen: 'img/paty-mm.png' },
    { id: 68, nombre: 'Paty-Pan Artesanal', descripcion: '40 hamburguesas de 125 grs con pan y aderezo', precio: 13620, imagen: 'img/paty-art.png' },
    { id: 69, nombre: 'Maxi Mesa-Fargo', descripcion: '40 hamburguesas de 110 grs con pan y aderezo ', precio: 11500, imagen: 'img/maxi-fargo.png' },
    { id: 70, nombre: 'Maxi Mesa-Mimago', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 8740, imagen: 'img/max-mm.png' },
    { id: 71, nombre: 'Maxi Mesa-Pan Artesanal', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 8930, imagen: 'img/max-art.png' },
    { id: 72, nombre: 'Boogys-Fargo', descripcion: '40 hamburguesas de 110 grs con pan y aderezo ', precio: 12820, imagen: 'img/boogiesfargo.png' },
    { id: 73, nombre: 'Boogys-Mimago', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 10050, imagen: 'img/boog-mm.png' },
    { id: 74, nombre: 'Boogys-Pan Artesanal', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 10240, imagen: 'img/boog-art.png' },
    { id: 75, nombre: 'Union Ganadera-Fargo', descripcion: '40 hamburguesas de 110 grs con pan y aderezo ', precio: 13420, imagen: 'img/union-fargo.png' },
    { id: 76, nombre: 'Union Ganadera-Mimago', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 10660, imagen: 'img/union-mm.png' },
    { id: 77, nombre: 'Union Ganadera-Pan Artesanal', descripcion: '40 hamburguesas de 110 grs con pan y aderezo', precio: 10850, imagen: 'img/victoria-art.png' },
    { id: 78, nombre: 'Maxi Mesa-Fargo', descripcion: '40 hamburguesas de 125 grs con pan y aderezo ', precio: 14290, imagen: 'img/maxi-fargo.png'  },
    { id: 79, nombre: 'Maxi Mesa-Mimago', descripcion: '40 hamburguesas de 125 grs con pan y aderezo', precio: 11530, imagen: 'img/max-mm.png' },
    { id: 80, nombre: 'Maxi Mesa-Pan Artesanal', descripcion: '40 hamburguesas de 125 grs con pan y aderezo', precio: 11720, imagen: 'img/max-art.png' },
    { id: 81, nombre: 'La Conquista-Fargo', descripcion: '30 hamburguesas de 69 grs con pan y aderezo ', precio: 12820, imagen: 'img/laconq-fargo.png' },
    { id: 82, nombre: 'La Conquista-Mimago', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 10050, imagen: 'img/laconq-mm.png' },
    { id: 83, nombre: 'La Conquista-Pan Artesanal', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 10240, imagen: 'img/laconq-art.png' },
    { id: 84, nombre: 'Pronto Beef-Fargo', descripcion: '30 hamburguesas de 69 grs con pan y aderezo ', precio: 13420, imagen: 'img/pronto-fargo.png' },
    { id: 85, nombre: 'Pronto Beef-Mimago', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 10660, imagen: 'img/pronto-mm.png' },
    { id: 86, nombre: 'Pronto Beef-Pan Artesanal', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 10850, imagen: 'img/pronto-art.png' },
    { id: 87, nombre: 'Victoria-Fargo', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 14290, imagen: 'img/victoria-fargo.png' },
    { id: 88, nombre: 'Victoria-Mimago', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 11530, imagen: 'img/victoria-mm.png' },
    { id: 89, nombre: 'Victoria-Pan Artesanal', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 11720, imagen: 'img/victoria-art.png' },
    { id: 90, nombre: 'Rancho Alto-Fargo', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 16190, imagen: 'img/rancho-fargo.png' },
    { id: 91, nombre: 'Rancho Alto-Mimago', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 13430, imagen: 'img/rancho-mm.png' },
    { id: 92, nombre: 'Rancho Alto-Pan Artesanal', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 13620, imagen: 'img/rancho-art.png' },
    { id: 93, nombre: 'Paty-Fargo', descripcion: '30 hamburguesas de 69 grs con pan y aderezo ', precio: 16190, imagen: 'img/paty-fargo.png' },
    { id: 94, nombre: 'Paty-Mimago', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 13430, imagen: 'img/paty-mm.png' },
    { id: 95, nombre: 'Paty-Pan Artesanal', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 13620, imagen: 'img/paty-art.png' },
    { id: 96, nombre: 'Swift-Fargo', descripcion: '30 hamburguesas de 69 grs con pan y aderezo ', precio: 11500, imagen: 'img/swift-fargo.png' },
    { id: 97, nombre: 'Swift-Mimago', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 8740, imagen: 'img/swift-mm.png' },
    { id: 98, nombre: 'Swift-Pan Artesanal', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 8930, imagen: 'img/swift-art.png' },
    { id: 99, nombre: 'Boogys-Fargo', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 12820, imagen: 'img/boogiesfargo.png' },
    { id: 100, nombre: 'Boogys-Mimago', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 10050, imagen: 'img/boog-mm.png' },
    { id: 101, nombre: 'Boogys-Pan Artesanal', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 10240, imagen: 'img/boog-art.png' },
    { id: 102, nombre: 'Union Ganadera-Fargo', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 13420, imagen: 'img/union-fargo.png' },
    { id: 103, nombre: 'Union Ganadera-Mimago', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 10660, imagen: 'img/union-mm.png' },
    { id: 104, nombre: 'Union Ganadera-Pan Artesanal', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 10850, imagen: 'img/union-art.png'},
    { id: 105, nombre: 'Maxi Mesa-Fargo', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 14290, imagen: 'img/maxi-fargo.png' },
    { id: 106, nombre: 'Maxi Mesa-Mimago', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 11530, imagen: 'img/max-mm.png' },
    { id: 107, nombre: 'Maxi Mesa-Pan Artesanal', descripcion: '30 hamburguesas de 69 grs con pan y aderezo', precio: 11720, imagen: 'img/max-art.png' },
    { id: 108, nombre: 'La Conquista-Fargo', descripcion: '60 hamburguesas de 69 grs con pan y aderezo ', precio: 12820, imagen: 'img/laconq-fargo.png' },
    { id: 109, nombre: 'La Conquista-Mimago', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 10050, imagen: 'img/laconq-mm.png' },
    { id: 110, nombre: 'La Conquista-Pan Artesanal', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 10240, imagen: 'img/laconq-art.png' },
    { id: 111, nombre: 'Pronto Beef-Fargo', descripcion: '60 hamburguesas de 69 grs con pan y aderezo ', precio: 13420, imagen: 'img/pronto-fargo.png' },
    { id: 112, nombre: 'Pronto Beef-Mimago', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 10660, imagen: 'img/pronto-mm.png' },
    { id: 113, nombre: 'Pronto Beef-Pan Artesanal', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 10850, imagen: 'img/pronto-art.png' },
    { id: 114, nombre: 'Victoria-Fargo', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 14290, imagen: 'img/victoria-fargo.png' },
    { id: 115, nombre: 'Victoria-Mimago', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 11530, imagen: 'img/victoria-mm.png' },
    { id: 116, nombre: 'Victoria-Pan Artesanal', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 11720, imagen: 'img/victoria-art.png' },
    { id: 117, nombre: 'Rancho Alto-Fargo', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 16190, imagen: 'img/rancho-fargo.png' },
    { id: 118, nombre: 'Rancho Alto-Mimago', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 13430, imagen: 'img/rancho-mm.png' },
    { id: 119, nombre: 'Rancho Alto-Pan Artesanal', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 13620, imagen: 'img/rancho-art.png' },
    { id: 120, nombre: 'Paty-Fargo', descripcion: '60 hamburguesas de 69 grs con pan y aderezo ', precio: 16190, imagen: 'img/paty-fargo.png' },
    { id: 121, nombre: 'Paty-Mimago', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 13430, imagen: 'img/paty-mm.png' },
    { id: 122, nombre: 'Paty-Pan Artesanal', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 13620, imagen: 'img/paty-art.png' },
    { id: 123, nombre: 'Swift-Fargo', descripcion: '60 hamburguesas de 69 grs con pan y aderezo ', precio: 11500, imagen: 'img/swift-fargo.png' },
    { id: 124, nombre: 'Swift-Mimago', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 8740, imagen: 'img/swift-mm.png' },
    { id: 125, nombre: 'Swift-Pan Artesanal', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 8930, imagen: 'img/swift-art.png' },
    { id: 126, nombre: 'Boogys-Fargo', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 12820, imagen: 'img/boogiesfargo.png' },
    { id: 127, nombre: 'Boogys-Mimago', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 10050, imagen: 'img/boog-mm.png' },
    { id: 128, nombre: 'Boogys-Pan Artesanal', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 10240, imagen: 'img/boog-art.png' },
    { id: 129, nombre: 'Union Ganadera-Fargo', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 10240, imagen: 'img/union-fargo.png' },
    { id: 130, nombre: 'Union Ganadera-Mimago', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 10660, imagen: 'img/union-mm.png' },
    { id: 131, nombre: 'Union Ganadera-Pan Artesanal', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 10850, imagen: 'img/union-art.png'},
    { id: 132, nombre: 'Maxi Mesa-Fargo', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 14290, imagen: 'img/maxi-fargo.png' },
    { id: 133, nombre: 'Maxi Mesa-Mimago', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 11530, imagen: 'img/max-mm.png' },
    { id: 134, nombre: 'Maxi Mesa-Pan Artesanal', descripcion: '60 hamburguesas de 69 grs con pan y aderezo', precio: 11720, imagen: 'img/max-art.png' },
    { id: 135, nombre: 'Maxi Mesa-Fargo', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 14290, imagen: 'img/maxi-fargo.png' },
    { id: 136, nombre: 'Maxi Mesa-Mimago', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 11530, imagen: 'img/max-mm.png' },
    { id: 137, nombre: 'Maxi Mesa-Pan Artesanal', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 11720, imagen: 'img/max-art.png' },
    { id: 138, nombre: 'Easy Beef-Fargo', descripcion: '30 hamburguesas de 83 grs con pan y aderezo ', precio: 10990, imagen: 'img/easyfargo.png' },
    { id: 139, nombre: 'Easy Beef-Mimago', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 8230, imagen: 'img/easymimago.png' },
    { id: 140, nombre: 'Easy Beef-Pan Artesanal', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 8420, imagen: 'img/easyart.png' },
    { id: 141, nombre: 'Rancho Alto-Fargo', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 16190, imagen: 'img/rancho-fargo.png' },
    { id: 142, nombre: 'Rancho Alto-Mimago', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 13430, imagen: 'img/rancho-mm.png' },
    { id: 143, nombre: 'Rancho Alto-Pan Artesanal', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 13620, imagen: 'img/rancho-art.png' },
    { id: 144, nombre: 'Paty-Fargo', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 16190, imagen: 'img/paty-fargo.png' },
    { id: 145, nombre: 'Paty-Mimago', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 13430, imagen: 'img/paty-mm.png' },
    { id: 146, nombre: 'Paty-Pan Artesanal', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 13620, imagen: 'img/paty-art.png' },
    { id: 147, nombre: 'Swift-Fargo', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 11500, imagen: 'img/swift-fargo.png' },
    { id: 148, nombre: 'Swift-Mimago', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 8740, imagen: 'img/swift-mm.png' },
    { id: 149, nombre: 'Swift-Pan Artesanal', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 8930, imagen: 'img/swift-art.png' },
    { id: 150, nombre: 'Boogys-Fargo', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 12820, imagen: 'img/boogiesfargo.png' },
    { id: 151, nombre: 'Boogys-Mimago', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 10050, imagen: 'img/boog-mm.png' },
    { id: 152, nombre: 'Boogys-Pan Artesanal', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 10240, imagen: 'img/boog-art.png' },
    { id: 153, nombre: 'Union Ganadera-Fargo', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 10240, imagen: 'img/union-fargo.png' },
    { id: 154, nombre: 'Union Ganadera-Mimago', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 10660, imagen: 'img/union-mm.png' },
    { id: 155, nombre: 'Union Ganadera-Pan Artesanal', descripcion: '30 hamburguesas de 83 grs con pan y aderezo', precio: 10850, imagen: 'img/union-art.png'},
    { id: 156, nombre: 'Maxi Mesa-Fargo', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 14290, imagen: 'img/maxi-fargo.png' },
    { id: 157, nombre: 'Maxi Mesa-Mimago', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 11530, imagen: 'img/max-mm.png' },
    { id: 158, nombre: 'Maxi Mesa-Pan Artesanal', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 11720, imagen: 'img/max-art.png' },
    { id: 159, nombre: 'Easy Beef-Fargo', descripcion: '48 hamburguesas de 83 grs con pan y aderezo ', precio: 10990, imagen: 'img/easyfargo.png' },
    { id: 160, nombre: 'Easy Beef-Mimago', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 8230, imagen: 'img/easymimago.png' },
    { id: 161, nombre: 'Easy Beef-Pan Artesanal', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 8420, imagen: 'img/easyart.png' },
    { id: 162, nombre: 'Rancho Alto-Fargo', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 16190, imagen: 'img/rancho-fargo.png' },
    { id: 163, nombre: 'Rancho Alto-Mimago', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 13430, imagen: 'img/rancho-mm.png' },
    { id: 164, nombre: 'Rancho Alto-Pan Artesanal', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 13620, imagen: 'img/rancho-art.png' },
    { id: 165, nombre: 'Paty-Fargo', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 16190, imagen: 'img/paty-fargo.png' },
    { id: 166, nombre: 'Paty-Mimago', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 13430, imagen: 'img/paty-mm.png' },
    { id: 167, nombre: 'Paty-Pan Artesanal', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 13620, imagen: 'img/paty-art.png' },
    { id: 168, nombre: 'Swift-Fargo', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 11500, imagen: 'img/swift-fargo.png' },
    { id: 169, nombre: 'Swift-Mimago', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 8740, imagen: 'img/swift-mm.png' },
    { id: 170, nombre: 'Swift-Pan Artesanal', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 8930, imagen: 'img/swift-art.png' },
    { id: 171, nombre: 'Boogys-Fargo', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 12820, imagen: 'img/boogiesfargo.png' },
    { id: 172, nombre: 'Boogys-Mimago', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 10050, imagen: 'img/boog-mm.png' },
    { id: 173, nombre: 'Boogys-Pan Artesanal', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 10240, imagen: 'img/boog-art.png' },
    { id: 174, nombre: 'Union Ganadera-Fargo', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 10240, imagen: 'img/union-fargo.png' },
    { id: 175, nombre: 'Union Ganadera-Mimago', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 10660, imagen: 'img/union-mm.png' },
    { id: 176, nombre: 'Union Ganadera-Pan Artesanal', descripcion: '48 hamburguesas de 83 grs con pan y aderezo', precio: 10850, imagen: 'img/union-art.png'},
    { id: 177, nombre: 'Delosan-Fargo', descripcion: '30 Panchos Cortos con pan y aderezo', precio: 16190, imagen: 'img/delosa-fargo.png' },
    { id: 178, nombre: 'Delosan-Mimago', descripcion: '30 Panchos Cortos con pan y aderezo', precio: 13430, imagen: 'img/delosa-mm.png' },
    { id: 179, nombre: 'Delosan-Pan Artesanal', descripcion: '30 Panchos Cortos con pan y aderezo', precio: 13620, imagen: 'img/delosa-art.png' },
    { id: 180, nombre: 'Bark-Fargo', descripcion: '30 Panchos Cortos con pan y aderezo', precio: 16190, imagen: 'img/barck-fargo.png' },
    { id: 181, nombre: 'Bark-Mimago', descripcion: '30 Panchos Cortos con pan y aderezo', precio: 13430, imagen: 'img/Barck-mm.png' },
    { id: 182, nombre: 'Bark-Pan Artesanal', descripcion: '30 Panchos Cortos con pan y aderezo', precio: 13620, imagen: 'img/barck-arte.png' },
    { id: 183, nombre: 'Vienissima-Fargo', descripcion: '30 Panchos Cortos con pan y aderezo', precio: 11500, imagen: 'img/vienisima-fargo.png' },
    { id: 184, nombre: 'Vienissima-Mimago', descripcion: '30 Panchos Cortos con pan y aderezo', precio: 8740, imagen: 'img/vienisima-mm.png' },
    { id: 185, nombre: 'Vienissima-Pan Artesanal', descripcion: '30 Panchos Cortos con pan y aderezo', precio: 8930, imagen: 'img/vienisima-art.png' },
    { id: 186, nombre: 'Paty Viena-Fargo', descripcion: '30 Panchos Cortos con pan y aderezo', precio: 12820, imagen: 'img/paty viena-fargo.png' },
    { id: 187, nombre: 'Paty Viena-Mimago', descripcion: '30 Panchos Cortos con pan y aderezo', precio: 10050, imagen: 'img/paty viena-mm.png' },
    { id: 188, nombre: 'Paty Viena-Pan Artesanal', descripcion: '30 Panchos Cortos con pan y aderezo', precio: 10240, imagen: 'img/paty viena-art.png' },
    { id: 189, nombre: 'Union Ganadera-Fargo', descripcion: '30 Panchos Cortos con pan y aderezo', precio: 10240, imagen: 'img/panch-union-fargo.png' },
    { id: 190, nombre: 'Union Ganadera-Mimago', descripcion: '30 Panchos Cortos con pan y aderezo', precio: 10660, imagen: 'img/panch-union-mm.png' },
    { id: 191, nombre: 'Union Ganadera-Pan Artesanal', descripcion: '30 Panchos Cortos con pan y aderezo', precio: 10850, imagen: 'img/panch-union-art.png'},
    { id: 192, nombre: 'Delosan-Fargo', descripcion: '36 Super Panchos con pan y aderezo', precio: 16190, imagen: 'img/delfarsp.png' },
    { id: 193, nombre: 'Delosan-Mimago', descripcion: '36 Super Panchos con pan y aderezo', precio: 13430, imagen: 'img/delmmsp.png' },
    { id: 194, nombre: 'Delosan-Pan Artesanal', descripcion: '36 Super Panchos con pan y aderezo', precio: 13620, imagen: 'img/delartsp.png' },
    { id: 195, nombre: 'Bark-Fargo', descripcion: '36 Super Panchos con pan y aderezo', precio: 16190, imagen: 'img/barfarsp.png' },
    { id: 196, nombre: 'Bark-Mimago', descripcion: '36 Super Panchos con pan y aderezo', precio: 13430, imagen: 'img/barmmsp.png' },
    { id: 197, nombre: 'Bark-Pan Artesanal', descripcion: '36 Super Panchos con pan y aderezo', precio: 13620, imagen: 'img/barmmsp.png' },
    { id: 198, nombre: 'Union Ganadera-Fargo', descripcion: '36 Super Panchos con pan y aderezo', precio: 10240, imagen: 'img/unfarsp.png' },
    { id: 199, nombre: 'Union Ganadera-Mimago', descripcion: '36 Super Panchos con pan y aderezo', precio: 10660, imagen: 'img/unmmsp.png' },
    { id: 200, nombre: 'Union Ganadera-Pan Artesanal', descripcion: '36 Super Panchos con pan y aderezo', precio: 10850, imagen: 'img/unartsp.png'},
    { id: 201, nombre: 'COMBO Riquitos', descripcion: 'COMBO Palitos, Papas fritas, Mani y Chizitos', precio: 3540, imagen: 'img/Rickcombo1.png' },
    { id: 202, nombre: 'COMBO Leq ', descripcion: 'COMBO Palitos, Papas fritas, Mani y Chizitos', precio: 33570, imagen: 'img/LeqCombo.png' },
    
];

function actualizarPrecio(id, nuevoPrecio) {
    const productoIndex = productos.findIndex(producto => producto.id === parseInt(id));
    if (productoIndex !== -1) {
        productos[productoIndex].precio = parseFloat(nuevoPrecio);
    }
}

function getProductos() {
    return productos;
}

module.exports = {
    getProductos,
    actualizarPrecio,  // Asegúrate de exportar la función actualizarPrecio
};